name         'KimNorgaard-httpfile'
version      '0.1.9'
source       'git://github.com/KimNorgaard/KimNorgaard-httpfile.git'
author       'Kim Norgaard'
summary      'Custom type for downloading files via HTTP and HTTPS'
description  'Uses checksums to determine whether the file should be downloaded or not'
license      'The MIT License (MIT)'
project_page 'https://github.com/KimNorgaard/KimNorgaard-httpfile'
